palette = "base16"

[palettes.base16]
black = "{{ background }}"
bright-black = "{{ muted }}"
white = "{{ foreground }}"
bright-white = "{{ bright_foreground }}"
red = "{{ red }}"
orange = "{{ orange }}"
yellow = "{{ yellow }}"
green = "{{ green }}"
cyan = "{{ cyan }}"
blue = "{{ blue }}"
magenta = "{{ magenta }}"
purple = "{{ magenta }}"
brown = "{{ brown }}"
bright-red = "{{ bright_red }}"
bright-yellow = "{{ bright_yellow }}"
bright-green = "{{ bright_green }}"
bright-cyan = "{{ bright_cyan }}"
bright-blue = "{{ bright_blue }}"
bright-magenta = "{{ bright_magenta }}"
bright-purple = "{{ bright_magenta }}"
