import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, relative } from "node:path";

const ZSHRC = join(homedir(), ".zshrc");
const REVIVE_FILE = join(homedir(), ".pi", "agent", "revive.zsh");
const DEFAULT_AGENT_DIR = join(homedir(), ".pi", "agent");

type Profile = {
  name: string;
  label: string;
  command: string;
  source: string;
  agentDir?: string;
};

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function expandHome(value: string): string {
  return value.replace(/^~(?=\/|$)/, homedir()).replace(/\$HOME/g, homedir());
}

function findAgentDir(text: string): string | undefined {
  const match = text.match(/PI_CODING_AGENT_DIR=(?:"([^"]+)"|'([^']+)'|([^\s\\]+))/);
  const value = match?.[1] ?? match?.[2] ?? match?.[3];
  return value ? expandHome(value) : undefined;
}

function copySessionIntoProfile(sessionFile: string, profile: Profile): string {
  if (!profile.agentDir) return sessionFile;

  const targetSessionsDir = join(profile.agentDir, "sessions");
  const sourceSessionsMarker = `${DEFAULT_AGENT_DIR}/sessions/`;
  const sessionSuffix = sessionFile.startsWith(sourceSessionsMarker)
    ? sessionFile.slice(sourceSessionsMarker.length)
    : relative(join(dirname(dirname(sessionFile))), sessionFile);
  const targetSessionFile = join(targetSessionsDir, sessionSuffix);

  if (targetSessionFile === sessionFile) return sessionFile;

  mkdirSync(dirname(targetSessionFile), { recursive: true });
  copyFileSync(sessionFile, targetSessionFile);
  return targetSessionFile;
}

function piEnvPrefix(profile: Profile): string {
  return profile.agentDir && profile.agentDir !== DEFAULT_AGENT_DIR
    ? `PI_CODING_AGENT_DIR=${shellQuote(profile.agentDir)} `
    : "env -u PI_CODING_AGENT_DIR ";
}

function writeReviveRequest(profile: Profile, sessionFile: string, cwd: string): void {
  writeFileSync(
    REVIVE_FILE,
    [
      "# Generated by ~/.pi/agent/extensions/pi-revive.ts",
      `PI_REVIVE_COMMAND=${shellQuote(profile.command)}`,
      `PI_REVIVE_AGENT_DIR=${shellQuote(profile.agentDir ?? DEFAULT_AGENT_DIR)}`,
      `PI_REVIVE_SESSION=${shellQuote(sessionFile)}`,
      `PI_REVIVE_CWD=${shellQuote(cwd)}`,
      "",
    ].join("\n"),
    "utf8",
  );
}

function scheduleExecRevive(profile: Profile, sessionFile: string, cwd: string): boolean {
  const execve = (process as typeof process & {
    execve?: (file: string, args: string[], env: Record<string, string>) => void;
  }).execve;

  if (typeof execve !== "function") return false;

  const command = `cd ${shellQuote(cwd)} && ${piEnvPrefix(profile)}${profile.command} --session ${shellQuote(sessionFile)}`;
  const env = Object.fromEntries(
    Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === "string"),
  );

  process.once("exit", () => {
    try {
      execve("/bin/zsh", ["zsh", "-ic", command], env);
    } catch (error) {
      console.error("Failed to exec Pi revive:", error);
    }
  });

  return true;
}

function discoverPiProfiles(): Profile[] {
  const profiles = new Map<string, Profile>();

  const add = (name: string, source: string, agentDir?: string) => {
    if (!/^pi(?:$|[-_][A-Za-z0-9_-]+$)/.test(name)) return;

    const existing = profiles.get(name);
    profiles.set(name, {
      name,
      label: source === "builtin" ? name : `${name} (${source})`,
      command: name,
      source: existing?.source ?? source,
      // Preserve the first discovered PI_CODING_AGENT_DIR so a wrapper function
      // cannot erase the real profile directory discovered from the original func.
      agentDir: existing?.agentDir ?? agentDir,
    });
  };

  add("pi", "builtin", DEFAULT_AGENT_DIR);

  if (!existsSync(ZSHRC)) return [...profiles.values()].sort((a, b) => a.name.localeCompare(b.name));

  const text = readFileSync(ZSHRC, "utf8");
  const lines = text.split(/\r?\n/);

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    const marker = line.match(/^#\s*pi-profile:\s*(pi(?:[-_][A-Za-z0-9_-]+)?)/i);
    if (marker?.[1]) {
      add(marker[1], ".zshrc marker");
      continue;
    }

    const aliasMatch = line.match(/^alias\s+(pi(?:[-_][A-Za-z0-9_-]+)?)=/);
    if (aliasMatch?.[1]) {
      add(aliasMatch[1], ".zshrc alias", findAgentDir(line));
      continue;
    }

    const fnMatch = line.match(/^(?:function\s+)?(pi(?:[-_][A-Za-z0-9_-]+)?)\s*\(\)\s*\{?/);
    if (fnMatch?.[1]) {
      const functionPreview = lines.slice(i, i + 8).join("\n");
      add(fnMatch[1], ".zshrc function", findAgentDir(functionPreview));
    }
  }

  return [...profiles.values()].sort((a, b) => a.name.localeCompare(b.name));
}

export default function (pi: ExtensionAPI) {
  pi.registerCommand("revive", {
    description: "Revive the current chat to another Pi profile from ~/.zshrc",
    getArgumentCompletions: (prefix: string) => {
      const profiles = discoverPiProfiles();
      const filtered = profiles.filter((profile) => profile.name.startsWith(prefix));
      return filtered.map((profile) => ({
        value: profile.name,
        label: profile.name,
        description: profile.source,
      }));
    },
    handler: async (args, ctx) => {
      await ctx.waitForIdle();

      const sessionFile = ctx.sessionManager.getSessionFile();
      if (!sessionFile) {
        ctx.ui.notify("Current chat is not saved (--no-session/ephemeral), so there is no session file to revive.", "error");
        return;
      }

      const profiles = discoverPiProfiles();
      if (profiles.length === 0) {
        ctx.ui.notify("No Pi profiles found in ~/.zshrc.", "error");
        return;
      }

      const requested = args.trim();
      const selectedName = requested || await ctx.ui.select(
        "Switch to Pi profile:",
        profiles.map((profile) => profile.name),
      );

      if (!selectedName) return;

      const profile = profiles.find((candidate) => candidate.name === selectedName);
      if (!profile) {
        ctx.ui.notify(`Unknown Pi profile: ${selectedName}. Try one of: ${profiles.map((p) => p.name).join(", ")}`, "error");
        return;
      }

      const targetSessionFile = copySessionIntoProfile(sessionFile, profile);
      const willExec = scheduleExecRevive(profile, targetSessionFile, ctx.cwd);
      if (!willExec) {
        writeReviveRequest(profile, targetSessionFile, ctx.cwd);
      }

      const historyNote = targetSessionFile === sessionFile ? "same session file" : "copied into target profile history";
      ctx.ui.notify(`Reviving to ${profile.name} with current chat (${historyNote})...`, "info");
      ctx.shutdown();
    },
  });
}
