model = "gpt-5.5"
model_reasoning_effort = "xhigh"
approval_policy = "never"
approvals_reviewer = "user"
sandbox_mode = "danger-full-access"
notify = ["/Users/danielkumlin/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/danielkumlin"]
trust_level = "trusted"

[projects."/Users/danielkumlin/.dotfiles"]
trust_level = "trusted"

[projects."/Users/danielkumlin/Projects/snack"]
trust_level = "trusted"

[projects."/Users/danielkumlin/Projects/apartment-search"]
trust_level = "trusted"

[projects."/Users/danielkumlin/General/Apartment papers"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[features]
hooks = true
multi_agent = true
js_repl = false

[plugins."github@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[desktop]
appearanceLightCodeThemeId = "vercel"
appearanceDarkCodeThemeId = "tokyo-night"
mac-menu-bar-enabled = false
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true

[desktop.appearanceLightChromeTheme]
accent = "#006aff"
contrast = 40
ink = "#171717"
opaqueWindows = true
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]
code = '"JetBrainsMono Nerd Font", ui-monospace, "Geist Mono"'
ui = '"Source Sans 3", Geist'

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#28a948"
diffRemoved = "#eb001d"
skill = "#a100f8"

[desktop.appearanceDarkChromeTheme]
accent = "#3d59a1"
contrast = 50
ink = "#a9b1d6"
opaqueWindows = true
surface = "#1a1b26"

[desktop.appearanceDarkChromeTheme.fonts]
code = '"JetBrainsMono Nerd Font", ui-monospace, "Geist Mono"'
ui = '"Source Sans 3", Geist'

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#449dab"
diffRemoved = "#914c54"
skill = "#9d7cd8"

[desktop.open-in-target-preferences]
global = "cursor"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/danielkumlin/.codex"
CODEX_HOME = "/Users/danielkumlin/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "496c7b3cb95b4bc20cff49b513150606e0da0000c92bf752206bee5a6c248423"
BROWSER_USE_AVAILABLE_BACKENDS = "iab"
BROWSER_USE_MARKETPLACE_NAME = "openai-bundled"
NODE_REPL_UNTRUSTED_ENV_ALLOWLIST = "BROWSER_USE_MARKETPLACE_NAME"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"
